### ISSUE TITLE
Error while deleting Namespace 

### ISSUE THREAD

**Issue by HolgerFerstl** [conplementAG/copsctl#27]
I can create a namespace but when i try to delete it, i get:
>copsctl.exe namespace delete --name test7
 _runtime error: invalid memory address or nil pointer dereference_

more info from the log file: 
>_Forbidden: User ... cannot delete resource ...  in API group ... at the cluster scope_ 

Full log can be found here:  
_P:\Ferstl\copsctl.log_

**Comment by hmrc87** [comment]
cannot reproduce it -- still valid?

**Comment by DenisBiondic** [comment]
closed - stale
